#!/usr/bin/env node
/**
 * One-command setup for Neon + DOKI.
 * Run: npm run setup
 * Prompts for Neon connection string (or use DATABASE_URL env var).
 * Creates .env, runs migrations, seeds catalog.
 */
import readline from 'readline';
import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, '.env');

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve((answer || '').trim());
    });
  });
}

function generateJwtSecret() {
  return crypto.randomBytes(32).toString('hex');
}

function envLooksValid(env) {
  const url = env.DATABASE_URL || '';
  const secret = env.JWT_SECRET || '';
  return (
    url.startsWith('postgresql://') &&
    url.includes('@') &&
    url.length > 30 &&
    secret.length >= 32 &&
    !secret.includes('your-secret') &&
    !secret.includes('xxx')
  );
}

function readExistingEnv() {
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, 'utf8');
  const out = {};
  for (const line of content.split('\n')) {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m) out[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

async function main() {
  console.log('\n🌸 DOKI — Neon setup\n');

  let dbUrl = process.env.DATABASE_URL;
  let jwtSecret = process.env.JWT_SECRET;
  const existing = readExistingEnv();

  if (!dbUrl) dbUrl = existing.DATABASE_URL;
  if (!jwtSecret) jwtSecret = existing.JWT_SECRET;

  const needsPrompt = !envLooksValid({ DATABASE_URL: dbUrl, JWT_SECRET: jwtSecret });

  if (needsPrompt) {
    console.log('You need a Neon connection string and a JWT secret.\n');
    console.log('Get your connection string:');
    console.log('  1. Go to https://console.neon.tech');
    console.log('  2. Open your project → Connection Details');
    console.log('  3. Copy the connection string (URI)\n');

    if (!dbUrl) {
      dbUrl = await ask('Paste your Neon connection string: ');
      if (!dbUrl || !dbUrl.startsWith('postgresql://')) {
        console.error('Invalid URL. Must look like: postgresql://user:pass@ep-xxx.region.aws.neon.tech/neondb?sslmode=require');
        process.exit(1);
      }
    }

    if (!jwtSecret || jwtSecret.length < 32) {
      const gen = await ask('Generate a random JWT_SECRET? (Y/n): ');
      jwtSecret = /^n$/i.test(gen) ? await ask('Enter your own JWT_SECRET (32+ chars): ') : generateJwtSecret();
      if (jwtSecret.length < 32) {
        console.error('JWT_SECRET must be at least 32 characters.');
        process.exit(1);
      }
    }
  }

  const envContent = `# DOKI — generated by setup
DATABASE_URL=${dbUrl}
JWT_SECRET=${jwtSecret}
PORT=3001
NODE_ENV=development
`;

  fs.writeFileSync(envPath, envContent);
  console.log('\n✓ Wrote .env');

  console.log('\nRunning migrations...');
  const migrate = spawnSync('node', ['backend/run-migrations.js'], {
    cwd: rootDir,
    stdio: 'inherit',
    env: { ...process.env, DATABASE_URL: dbUrl, JWT_SECRET: jwtSecret },
  });
  if (migrate.status !== 0) {
    console.error('\n✗ Migrations failed.');
    process.exit(1);
  }

  console.log('\nSeeding catalog...');
  const seed = spawnSync('node', ['backend/run-seeds.js'], {
    cwd: rootDir,
    stdio: 'inherit',
    env: { ...process.env, DATABASE_URL: dbUrl, JWT_SECRET: jwtSecret },
  });
  if (seed.status !== 0) {
    console.error('\n✗ Seeding failed.');
    process.exit(1);
  }

  console.log('\nBuilding web app...');
  const build = spawnSync('npm', ['run', 'build:web'], {
    cwd: rootDir,
    stdio: 'inherit',
    shell: true,
  });
  if (build.status !== 0) {
    console.warn('\n⚠ Web build failed (you can run npm run build:web later).');
  } else {
    console.log('✓ Web app built');
  }

  console.log('\n✅ Setup complete!\n');
  console.log('To run:');
  console.log('  npm run backend');
  console.log('Then open http://localhost:3001 in your browser.\n');
  console.log('For mobile: npm run frontend, then scan QR with Expo Go.\n');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
